// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple powerpc-unknown-unknown -O2 -emit-llvm %s -o - \
// RUN:   -target-cpu pwr7 | FileCheck %s -check-prefix=CHECK-POWERPC
// RUN: %clang_cc1 -triple powerpc64le-unknown-unknown -O2 -emit-llvm %s -o - \
// RUN:   -target-cpu pwr7 | FileCheck %s -check-prefix=CHECK-POWERPC-LE

typedef __INT8_TYPE__    int8_t;
typedef __INT16_TYPE__   int16_t;
typedef __INT32_TYPE__   int32_t;
typedef __INT64_TYPE__   int64_t;
typedef __UINT8_TYPE__   uint8_t;
typedef __UINT16_TYPE__  uint16_t;
typedef __UINT32_TYPE__  uint32_t;
typedef __UINT64_TYPE__  uint64_t;

// ============================================
// Arithmetic Operations
// ============================================

// CHECK-POWERPC-LABEL: define dso_local noundef half @c_add(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[UNPROMOTION:%.*]] = fadd half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    ret half [[UNPROMOTION]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @c_add(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[UNPROMOTION:%.*]] = fadd half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    ret half [[UNPROMOTION]]
//
_Float16 c_add(_Float16 a, _Float16 b) { return a + b; }

// CHECK-POWERPC-LABEL: define dso_local noundef half @c_sub(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[UNPROMOTION:%.*]] = fsub half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    ret half [[UNPROMOTION]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @c_sub(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[UNPROMOTION:%.*]] = fsub half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    ret half [[UNPROMOTION]]
//
_Float16 c_sub(_Float16 a, _Float16 b) { return a - b; }

// CHECK-POWERPC-LABEL: define dso_local noundef half @c_mul(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[UNPROMOTION:%.*]] = fmul half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    ret half [[UNPROMOTION]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @c_mul(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[UNPROMOTION:%.*]] = fmul half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    ret half [[UNPROMOTION]]
//
_Float16 c_mul(_Float16 a, _Float16 b) { return a * b; }

// CHECK-POWERPC-LABEL: define dso_local noundef half @c_div(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[UNPROMOTION:%.*]] = fdiv half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    ret half [[UNPROMOTION]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @c_div(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[UNPROMOTION:%.*]] = fdiv half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    ret half [[UNPROMOTION]]
//
_Float16 c_div(_Float16 a, _Float16 b) { return a / b; }

// ============================================
// Unary Operations
// ============================================

// CHECK-POWERPC-LABEL: define dso_local noundef half @c_neg(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[UNPROMOTION:%.*]] = fneg half [[A]]
// CHECK-POWERPC-NEXT:    ret half [[UNPROMOTION]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @c_neg(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[UNPROMOTION:%.*]] = fneg half [[A]]
// CHECK-POWERPC-LE-NEXT:    ret half [[UNPROMOTION]]
//
_Float16 c_neg(_Float16 a) { return -a; }

// ============================================
// Compare Operations
// ============================================

// CHECK-POWERPC-LABEL: define dso_local range(i32 0, 2) i32 @c_eq(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CMP:%.*]] = fcmp oeq half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-NEXT:    ret i32 [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local signext range(i32 0, 2) i32 @c_eq(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CMP:%.*]] = fcmp oeq half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-LE-NEXT:    ret i32 [[CONV]]
//
int c_eq(_Float16 a, _Float16 b){ return a == b; }

// CHECK-POWERPC-LABEL: define dso_local range(i32 0, 2) i32 @c_ne(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CMP:%.*]] = fcmp une half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-NEXT:    ret i32 [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local signext range(i32 0, 2) i32 @c_ne(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CMP:%.*]] = fcmp une half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-LE-NEXT:    ret i32 [[CONV]]
//
int c_ne(_Float16 a, _Float16 b){ return a != b; }

// CHECK-POWERPC-LABEL: define dso_local range(i32 0, 2) i32 @c_lt(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CMP:%.*]] = fcmp olt half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-NEXT:    ret i32 [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local signext range(i32 0, 2) i32 @c_lt(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CMP:%.*]] = fcmp olt half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-LE-NEXT:    ret i32 [[CONV]]
//
int c_lt(_Float16 a, _Float16 b){ return a <  b; }

// CHECK-POWERPC-LABEL: define dso_local range(i32 0, 2) i32 @c_le(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CMP:%.*]] = fcmp ole half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-NEXT:    ret i32 [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local signext range(i32 0, 2) i32 @c_le(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CMP:%.*]] = fcmp ole half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-LE-NEXT:    ret i32 [[CONV]]
//
int c_le(_Float16 a, _Float16 b){ return a <= b; }

// CHECK-POWERPC-LABEL: define dso_local range(i32 0, 2) i32 @c_gt(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CMP:%.*]] = fcmp ogt half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-NEXT:    ret i32 [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local signext range(i32 0, 2) i32 @c_gt(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CMP:%.*]] = fcmp ogt half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-LE-NEXT:    ret i32 [[CONV]]
//
int c_gt(_Float16 a, _Float16 b){ return a >  b; }

// CHECK-POWERPC-LABEL: define dso_local range(i32 0, 2) i32 @c_ge(
// CHECK-POWERPC-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CMP:%.*]] = fcmp oge half [[A]], [[B]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-NEXT:    ret i32 [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local signext range(i32 0, 2) i32 @c_ge(
// CHECK-POWERPC-LE-SAME: half noundef [[A:%.*]], half noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CMP:%.*]] = fcmp oge half [[A]], [[B]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-POWERPC-LE-NEXT:    ret i32 [[CONV]]
//
int c_ge(_Float16 a, _Float16 b){ return a >= b; }

// ============================================
// Conversion Operations: half <-> float/double
// ============================================

// CHECK-POWERPC-LABEL: define dso_local noundef float @to_f32(
// CHECK-POWERPC-SAME: half noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = fpext half [[X]] to float
// CHECK-POWERPC-NEXT:    ret float [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef float @to_f32(
// CHECK-POWERPC-LE-SAME: half noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = fpext half [[X]] to float
// CHECK-POWERPC-LE-NEXT:    ret float [[CONV]]
//
float to_f32(_Float16 x){ return (float)x; }

// CHECK-POWERPC-LABEL: define dso_local noundef double @to_f64(
// CHECK-POWERPC-SAME: half noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = fpext half [[X]] to double
// CHECK-POWERPC-NEXT:    ret double [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef double @to_f64(
// CHECK-POWERPC-LE-SAME: half noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = fpext half [[X]] to double
// CHECK-POWERPC-LE-NEXT:    ret double [[CONV]]
//
double to_f64(_Float16 x){ return (double)x; }

// CHECK-POWERPC-LABEL: define dso_local noundef half @from_f32(
// CHECK-POWERPC-SAME: float noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = fptrunc float [[X]] to half
// CHECK-POWERPC-NEXT:    ret half [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @from_f32(
// CHECK-POWERPC-LE-SAME: float noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = fptrunc float [[X]] to half
// CHECK-POWERPC-LE-NEXT:    ret half [[CONV]]
//
_Float16 from_f32(float  x){ return (_Float16)x; }

// CHECK-POWERPC-LABEL: define dso_local noundef half @from_f64(
// CHECK-POWERPC-SAME: double noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-NEXT:    [[CONV:%.*]] = fptrunc double [[X]] to half
// CHECK-POWERPC-NEXT:    ret half [[CONV]]
//
// CHECK-POWERPC-LE-LABEL: define dso_local noundef half @from_f64(
// CHECK-POWERPC-LE-SAME: double noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-POWERPC-LE-NEXT:  [[ENTRY:.*:]]
// CHECK-POWERPC-LE-NEXT:    [[CONV:%.*]] = fptrunc double [[X]] to half
// CHECK-POWERPC-LE-NEXT:    ret half [[CONV]]
//
_Float16 from_f64(double x){ return (_Float16)x; }
