; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs -mtriple=powerpc-ibm-aix -mcpu=pwr7 < %s | FileCheck %s --check-prefix=P7-AIX
; RUN: llc -verify-machineinstrs -mtriple=powerpc-ibm-aix -mcpu=pwr8 < %s | FileCheck %s --check-prefix=P8-AIX
; RUN: llc -verify-machineinstrs -mtriple=powerpc-ibm-aix -mcpu=pwr9 -mattr=+vsx,+power9-vector < %s | FileCheck %s --check-prefix=P9-AIX
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-linux-gnu -mcpu=pwr7 < %s | FileCheck %s --check-prefix=P7-LINUX
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-linux-gnu -mcpu=pwr8 < %s | FileCheck %s --check-prefix=P8-LINUX
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-linux-gnu -mcpu=pwr9 -mattr=+vsx,+power9-vector < %s | FileCheck %s --check-prefix=P9-LINUX

; ============================================
; Basic Arithmetic Operations
; ============================================

define half @op_add(half %a, half %b) {
; P7-AIX-LABEL: op_add:
; P7-AIX:       # %bb.0: # %entry
; P7-AIX-NEXT:    mflr 0
; P7-AIX-NEXT:    stwu 1, -80(1)
; P7-AIX-NEXT:    stw 0, 88(1)
; P7-AIX-NEXT:    stw 31, 68(1) # 4-byte Folded Spill
; P7-AIX-NEXT:    clrlwi 31, 3, 16
; P7-AIX-NEXT:    clrlwi 3, 4, 16
; P7-AIX-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P7-AIX-NEXT:    bl .__extendhfsf2[PR]
; P7-AIX-NEXT:    nop
; P7-AIX-NEXT:    mr 3, 31
; P7-AIX-NEXT:    fmr 31, 1
; P7-AIX-NEXT:    bl .__extendhfsf2[PR]
; P7-AIX-NEXT:    nop
; P7-AIX-NEXT:    fadds 1, 1, 31
; P7-AIX-NEXT:    bl .__truncsfhf2[PR]
; P7-AIX-NEXT:    nop
; P7-AIX-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P7-AIX-NEXT:    lwz 31, 68(1) # 4-byte Folded Reload
; P7-AIX-NEXT:    addi 1, 1, 80
; P7-AIX-NEXT:    lwz 0, 8(1)
; P7-AIX-NEXT:    mtlr 0
; P7-AIX-NEXT:    blr
;
; P8-AIX-LABEL: op_add:
; P8-AIX:       # %bb.0: # %entry
; P8-AIX-NEXT:    mflr 0
; P8-AIX-NEXT:    stwu 1, -80(1)
; P8-AIX-NEXT:    stw 0, 88(1)
; P8-AIX-NEXT:    stw 31, 68(1) # 4-byte Folded Spill
; P8-AIX-NEXT:    clrlwi 31, 3, 16
; P8-AIX-NEXT:    clrlwi 3, 4, 16
; P8-AIX-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-NEXT:    nop
; P8-AIX-NEXT:    mr 3, 31
; P8-AIX-NEXT:    fmr 31, 1
; P8-AIX-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-NEXT:    nop
; P8-AIX-NEXT:    xsaddsp 1, 1, 31
; P8-AIX-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-NEXT:    nop
; P8-AIX-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-NEXT:    lwz 31, 68(1) # 4-byte Folded Reload
; P8-AIX-NEXT:    addi 1, 1, 80
; P8-AIX-NEXT:    lwz 0, 8(1)
; P8-AIX-NEXT:    mtlr 0
; P8-AIX-NEXT:    blr
;
; P9-AIX-LABEL: op_add:
; P9-AIX:       # %bb.0: # %entry
; P9-AIX-NEXT:    clrlwi 3, 3, 16
; P9-AIX-NEXT:    clrlwi 4, 4, 16
; P9-AIX-NEXT:    mtfprwz 0, 4
; P9-AIX-NEXT:    mtfprwz 1, 3
; P9-AIX-NEXT:    xscvhpdp 0, 0
; P9-AIX-NEXT:    xscvhpdp 1, 1
; P9-AIX-NEXT:    xsaddsp 0, 1, 0
; P9-AIX-NEXT:    xscvdphp 0, 0
; P9-AIX-NEXT:    mffprwz 3, 0
; P9-AIX-NEXT:    blr
;
; P7-LINUX-LABEL: op_add:
; P7-LINUX:       # %bb.0: # %entry
; P7-LINUX-NEXT:    mflr 0
; P7-LINUX-NEXT:    .cfi_def_cfa_offset 64
; P7-LINUX-NEXT:    .cfi_offset lr, 16
; P7-LINUX-NEXT:    .cfi_offset r30, -24
; P7-LINUX-NEXT:    .cfi_offset f31, -8
; P7-LINUX-NEXT:    std 30, -24(1) # 8-byte Folded Spill
; P7-LINUX-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P7-LINUX-NEXT:    stdu 1, -64(1)
; P7-LINUX-NEXT:    mr 30, 3
; P7-LINUX-NEXT:    clrldi 3, 4, 48
; P7-LINUX-NEXT:    std 0, 80(1)
; P7-LINUX-NEXT:    bl __extendhfsf2
; P7-LINUX-NEXT:    nop
; P7-LINUX-NEXT:    clrldi 3, 30, 48
; P7-LINUX-NEXT:    fmr 31, 1
; P7-LINUX-NEXT:    bl __extendhfsf2
; P7-LINUX-NEXT:    nop
; P7-LINUX-NEXT:    fadds 1, 1, 31
; P7-LINUX-NEXT:    bl __truncsfhf2
; P7-LINUX-NEXT:    nop
; P7-LINUX-NEXT:    addi 1, 1, 64
; P7-LINUX-NEXT:    ld 0, 16(1)
; P7-LINUX-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P7-LINUX-NEXT:    ld 30, -24(1) # 8-byte Folded Reload
; P7-LINUX-NEXT:    mtlr 0
; P7-LINUX-NEXT:    blr
;
; P8-LINUX-LABEL: op_add:
; P8-LINUX:       # %bb.0: # %entry
; P8-LINUX-NEXT:    mflr 0
; P8-LINUX-NEXT:    .cfi_def_cfa_offset 64
; P8-LINUX-NEXT:    .cfi_offset lr, 16
; P8-LINUX-NEXT:    .cfi_offset r30, -24
; P8-LINUX-NEXT:    .cfi_offset f31, -8
; P8-LINUX-NEXT:    std 30, -24(1) # 8-byte Folded Spill
; P8-LINUX-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-NEXT:    stdu 1, -64(1)
; P8-LINUX-NEXT:    mr 30, 3
; P8-LINUX-NEXT:    clrldi 3, 4, 48
; P8-LINUX-NEXT:    std 0, 80(1)
; P8-LINUX-NEXT:    bl __extendhfsf2
; P8-LINUX-NEXT:    nop
; P8-LINUX-NEXT:    clrldi 3, 30, 48
; P8-LINUX-NEXT:    fmr 31, 1
; P8-LINUX-NEXT:    bl __extendhfsf2
; P8-LINUX-NEXT:    nop
; P8-LINUX-NEXT:    xsaddsp 1, 1, 31
; P8-LINUX-NEXT:    bl __truncsfhf2
; P8-LINUX-NEXT:    nop
; P8-LINUX-NEXT:    addi 1, 1, 64
; P8-LINUX-NEXT:    ld 0, 16(1)
; P8-LINUX-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-NEXT:    ld 30, -24(1) # 8-byte Folded Reload
; P8-LINUX-NEXT:    mtlr 0
; P8-LINUX-NEXT:    blr
;
; P9-LINUX-LABEL: op_add:
; P9-LINUX:       # %bb.0: # %entry
; P9-LINUX-NEXT:    clrlwi 3, 3, 16
; P9-LINUX-NEXT:    clrlwi 4, 4, 16
; P9-LINUX-NEXT:    mtfprwz 0, 4
; P9-LINUX-NEXT:    mtfprwz 1, 3
; P9-LINUX-NEXT:    xscvhpdp 0, 0
; P9-LINUX-NEXT:    xscvhpdp 1, 1
; P9-LINUX-NEXT:    xsaddsp 0, 1, 0
; P9-LINUX-NEXT:    xscvdphp 0, 0
; P9-LINUX-NEXT:    mffprwz 3, 0
; P9-LINUX-NEXT:    blr
  entry:
  %unpromotion = fadd half %a, %b
  ret half %unpromotion
}
