; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-unknown-linux-gnu \
; RUN:     -mcpu=pwr9 < %s | FileCheck %s

; Basic comparison with branch
define i32 @test_br_cc_olt(half %a, half %b) {
; CHECK-LABEL: test_br_cc_olt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 16
; CHECK-NEXT:    clrlwi 4, 4, 16
; CHECK-NEXT:    mtfprwz 0, 4
; CHECK-NEXT:    mtfprwz 1, 3
; CHECK-NEXT:    xscvhpdp 0, 0
; CHECK-NEXT:    xscvhpdp 1, 1
; CHECK-NEXT:    fcmpu 0, 1, 0
; CHECK-NEXT:    bge 0, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    li 3, 1
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB0_2: # %if.else
; CHECK-NEXT:    li 3, 0
; CHECK-NEXT:    blr
  %cmp = fcmp olt half %a, %b
  br i1 %cmp, label %if.then, label %if.else
if.then:
  ret i32 1
if.else:
  ret i32 0
}

; Test with constant
define i32 @test_br_cc_constant(half %a) {
; CHECK-LABEL: test_br_cc_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 16
; CHECK-NEXT:    xxlxor 1, 1, 1
; CHECK-NEXT:    mtfprwz 0, 3
; CHECK-NEXT:    xscvhpdp 0, 0
; CHECK-NEXT:    fcmpu 0, 0, 1
; CHECK-NEXT:    ble 0, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    li 3, 1
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB1_2: # %if.else
; CHECK-NEXT:    li 3, 0
; CHECK-NEXT:    blr
  %cmp = fcmp ogt half %a, 0xH0000
  br i1 %cmp, label %if.then, label %if.else
if.then:
  ret i32 1
if.else:
  ret i32 0
}

; vector reduction + branch
define fastcc i16 @test_vector_reduce_br(half %arg) {
; CHECK-LABEL: test_vector_reduce_br:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 16
; CHECK-NEXT:    xxlxor 1, 1, 1
; CHECK-NEXT:    mtfprwz 0, 3
; CHECK-NEXT:    xscvhpdp 0, 0
; CHECK-NEXT:    fcmpu 0, 0, 1
; CHECK-NEXT:    bc 12, 0, .LBB2_3
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    fcmpu 0, 0, 0
; CHECK-NEXT:    bc 12, 3, .LBB2_3
; CHECK-NEXT:  # %bb.2: # %taken
; CHECK-NEXT:    li 3, 0
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB2_3: # %not_taken
; CHECK-NEXT:    li 3, 1
; CHECK-NEXT:    blr
  %reduce = tail call half @llvm.vector.reduce.fmin.v4f16(<4 x half> zeroinitializer)
  %cmp = fcmp ole half %reduce, %arg
  br i1 %cmp, label %taken, label %not_taken
taken:
  ret i16 0
not_taken:
  ret i16 1
}

declare half @llvm.vector.reduce.fmin.v4f16(<4 x half>)
